# @host = http://localhost:8887
@host = http://106.75.67.107:8888/open_admin

###
@userId = 12312313123123213123
POST {{host}}/token/list HTTP/1.1
content-type: application/json

{
    "pageNum": 1,
    "pageSize": 10
}

###
POST {{host}}/openPlatform/verifyToken HTTP/1.1
content-type: application/json

{
    "userId": "12312313123123213123",
    "openToken": "2956229d50c578f53198ccea94d9f04c",
    "verifyToken": "ver12312313123123213123"
}

