@host = http://localhost:8888/open_admin
# @host=http://106.75.67.107/open_admin
@content-json-type = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNDU0MjA2MywiZXhwIjoxNjM0NTc4MDYzfQ.T_oFBgeAPjcNdy6LcSzTpK2bCrf-wNWt1sbstEfk2-w

### 获取操作记录列表
GET {{host}}/operation/list HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "pageNum": 1,
    "pageSize": 10
}