###
GET http://localhost:8887/status/ping HTTP/1.1

###
POST http://localhost:8887/status/ping HTTP/1.1
content-type: application/json

{
    "name": "name"
}

### 
GET http://localhost:8887/config/pageConfig HTTP/1.1