# @host = http://localhost:8888/open_admin
@host=http://106.75.67.107:8888/open_admin
@content-json-type = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNTg0Njk2OSwiZXhwIjoxNjM1ODgyOTY5fQ.2FbmP7mvuCpEy6y_Rz-Iw9ZEy6i3NqVMKRD2vmNJczE

### 获取Token列表
GET {{host}}/token/list HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "pageNum": 1,
    "pageSize": 10
}


### 获取Token详情
GET {{host}}/token/detail HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "id": 39
}

### 审核Token
POST {{host}}/token/verify HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "id": 38,
    "status": 1,
    "remark": "token名称错误"
}

### 获取币价
GET {{host}}/token/getPrice?symbol=&currency=usdt&chain=&contract= HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}