# @host = http://localhost:8888/open_admin
@host=http://106.75.67.107:8888/open_admin
@content-json-type = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNDc4NDk4MiwiZXhwIjoxNjM0ODIwOTgyfQ.jWfGhjMOEvsJDIjrc7_bPZrgCkyUziu9ASPRFF5QrYk

### 获取Token列表
GET {{host}}/token/list HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "pageNum": 1,
    "pageSize": 10
}

### 审核Token
POST {{host}}/token/verify HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "id": 1,
    "status": 1,
    "remark": "token名称错误"
}