# @host = http://localhost:8888/open_admin
@host=http://106.75.67.107:8888/open_admin
@content-json-type = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNDYyODg3MywiZXhwIjoxNjM0NjY0ODczfQ.7xI2uQNQNrOhYhAqkV4cp6mACyzTmufU31f840frEbE

### user login
POST {{host}}/user/login HTTP/1.1
content-type: {{content-json-type}}

{
    "loginName": "chenxiaokang",
    "password": "chenxiaokang"
}

### update user
POST {{host}}/user/update HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "id": "1",
    "loginName": "chenxiaokang",
    "password": "chenxiaokang"
}

### add user
POST {{host}}/user/update HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "loginName": "chenxiaokang2",
    "password": "chenxiaokang"
}

### list user
POST {{host}}/user/list HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "pageNum": 1,
    "pageSize": 10
}


### ms_language batchPost
POST http://localhost:8893/batchPost HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "module": "open",
    "table": "Token",
    "data": [{"lang":"en","id":1,"data":{"name":"23"}},{"data":{"name":"123cn"},"lang":"cn","id":1},{"data":{"name":"123dn"},"lang":"dn","id":1}]
}

### ms_language batchGet
GET http://localhost:8893/batchGet?module=open&table=token&id=1 HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}
