@host = http://localhost:8888/open_admin
# @host=http://106.75.67.107/open_admin
@content-json-type = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNDU0MjA2MywiZXhwIjoxNjM0NTc4MDYzfQ.T_oFBgeAPjcNdy6LcSzTpK2bCrf-wNWt1sbstEfk2-w

### user login
POST {{host}}/user/login HTTP/1.1
content-type: {{content-json-type}}

{
    "loginName": "chenxiaokang",
    "password": "chenxiaokang"
}

### update user
POST {{host}}/user/update HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "id": "1",
    "loginName": "chenxiaokang",
    "password": "chenxiaokang"
}

### add user
POST {{host}}/user/update HTTP/1.1
content-type: {{content-json-type}}
token: {{token}}

{
    "loginName": "chenxiaokang2",
    "password": "chen"
}